### ISSUE TITLE
Unhelpful exception raised when IPython is not installed

### ISSUE THREAD

**Issue by xigrug** [GenericMappingTools/gmt-python#108]
gmt/tests/test_figure.py::test_figure_show <- /soft/anaconda2/envs/python3.6/lib/python3.6/site-packages/gmt_python-0+unknown-py3.6.egg/gmt/tests/test_figure.py FAILED [ 80%]
E TypeError: 'NoneType' object is not callable

/soft/anaconda2/envs/python3.6/lib/python3.6/site-packages/gmt_python-0+unknown-py3.6.egg/gmt/figure.py:308: TypeError

It doesn't work when I am tring
fig_alias = gmt.Figure()
fig_alias.coast(R='-90/-70/0/20', J='M6i', G='gray', S='blue', B=True)
fig_alias.show()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/users1j/cliu/soft/anaconda2/envs/python3.6/lib/python3.6/site-packages/gmt_python-0+unknown-py3.6.egg/gmt/figure.py", line 308, in show
img = Image(data=png, width=width)
TypeError: 'NoneType' object is not callable

**Comment by xigrug** [comment]
conda install  IPython solve this problem

**Comment by leouieda** [comment]
@xigrug thanks for reporting. The error message should be better in this case. If you're not running on the Jupyter notebook, use the argument `external=True` to open an external PDF viewer.
