### ISSUE TITLE
Interactive globe in the Jupyter notebook not working in Firefox Quantum 58.0.1

### ISSUE THREAD

**Issue by rafaelmds** [GenericMappingTools/gmt-python#134]
## Full code/command that generated the error

I executed all cells in http://try.gmtpython.xyz and the last one didn't output the desired result, instead it just output a blank background image.

I also tried to run locally, but the result was the same, no globe output.

## Full error message

Any printed error.

## System information

* Operating system: Linux debian (9.3) 4.9.65-3+deb9u2
* Python installation (Anaconda, system, ETS): conda 4.4.10
* Version of GMT/Python: I don't know, commit 270880619. libgmt is 6.0.0, Python 3.6.4, jupyter-notebook 5.2.2
* Browser: Firefox Quantum 58.0.1
* How you installed GMT/Python: cloned repo, created conda env, make develop, set LD_LIBRARY_PATH

__*mybinder*__
![gmt-globe-online](https://user-images.githubusercontent.com/9625617/36511695-709d6824-1746-11e8-9cf1-2881a0209c9e.png)

__*local*__
![gmt-globe-local](https://user-images.githubusercontent.com/9625617/36511946-8cb32494-1747-11e8-86f8-b7a7b6cb8828.png)

**Comment by leouieda** [comment]
Thanks, Rafael. I can confirm the bug on my own machine with Firefox 58.0.2. Don't what happened because it was working yesterday with the exact same specs. It might have been something in WorldWind that changed. I'll investigate further.

**Comment by rafaelmds** [comment]
The laptop has a nvidia optimus.

I'm using i915 for the Intel and bumblebee with nvidia proprietary driver.

I can confirm it **is working** using optirun (to use nvidia proprietary driver) to launch jupyter notebook and firefox.

**Comment by leouieda** [comment]
Yep, it's a graphics card problem for the webgl rendering. I had upgrade my driver yesterday and that was what broke it for me. Managed to get it working again with the proprietary nvidia driver on my desktop.

OK, so it seems like it's not really a bug. I don't imagine many people will run into this issue using bumblebee. 

Thanks for opening the issue and trying it out!
