### ISSUE TITLE
Let Figure.plot() accept list as arguments

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt-python#139]
*If this is a **question or feature request**, delete the above lines and instead:*

* Describe the feature you desire in as much detail as possible:
Current Figure.plot() doesn't accept lists of x and y as arguments. Code below will report an error:

```python
import gmt

region = [150, 240, -10, 60]
x = [160, 170, 180]
y = [20, 30, 50]

fig = gmt.Figure()
# Create a 6x6 inch basemap using the data region
fig.basemap(region=region, projection='X6i', frame=True)
# Plot using triangles (i) of 0.3 cm
fig.plot(x, y, style='i0.3c', color='black')
fig.show()
```

* Are you willing to try to implement and maintain this feature? 
  We'll help you through the process.

  Yes.

**Comment by leouieda** [comment]
@seisman that's a great idea! 

You can plug the conversion of a list to a numpy array in the [`vectors_to_arrays` function in `gmt/clib/utils.py`](https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/utils.py#L51). Specifically, it would be best to generalize the [`_series_to_array`](https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/utils.py#L98) function to convert anything to a 1D array (just `_to_array` or `_as_array`). For now it will handle lists and pandas.Series but we can add more things later if we need.

This function touches a lot of places so it would be good to have tests in:

* Doctest in `_series_to_array`: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/utils.py#L98
* Doctest in `vectors_to_arrays`: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/utils.py#L12
* Doctest in `LibGMT.vectors_to_vfile`: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/clib/core.py#L884 (maybe use x=list, y=numpy array, and z=pandas.Series in the existing example)
* Unit test in `test_clib.py`: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/tests/test_clib.py#L514

**Comment by leouieda** [comment]
Feel free to assign yourself to the issue if you want to work on this.
