### ISSUE TITLE
Make sure 'LibGMT.log_to_file' removes the file even if an exception occurs

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt-python#174]
Right now, it doesn't check that the log file is deleted if there was an error in setting the logging or an exception occurs inside the `with` block. I would guess that it isn't. It be good to implement a test to make sure the file is deleted.

**Comment by seisman** [comment]
It seems this issue can be closed since #188 remove the `log_to_file` function.

**Comment by leouieda** [comment]
:+1:
