### ISSUE TITLE
Broken links in README.rst

### ISSUE THREAD

**Issue by wckoeppen** [GenericMappingTools/gmt-python#191]
Looks like the link to the tutorials in the main readme:
https://github.com/GenericMappingTools/gmt-python/blob/master/README.rst

is pointing to a location that's not redirecting:
https://www.gmtpython.xyz/tutorials

though I can navigate to them here:
https://www.gmtpython.xyz/latest/tutorials/index.html

**Comment by leouieda** [comment]
@wckoeppen thanks for spotting that! It's actually all the links in the README.

I recently (#187) changed the documentation layout to prepare for future releases. I should have done this from the start.

Would you like to try editing the README yourself?

**Comment by wckoeppen** [comment]
Whoops, yes, I could have done that. Though now it looks like you already have a branch with the corrected links.

**Comment by leouieda** [comment]
That was a "whoops" on my part. I started and then thought that you might want to do it. I haven't finished it yet if you want to take a shot. Need to check if these links appear anywhere else.

**Comment by leouieda** [comment]
No pressure if you don't feel like it, though. I'm just happy to help people get involved however they can.
