### ISSUE TITLE
gmt.test() error

### ISSUE THREAD

**Issue by GengPeiLin** [GenericMappingTools/gmt-python#226]
**Description of the problem**

Today I start with a new conda env and everything go smoothly and beautifully.
import gmt in ipython without any error, but gmt.test() show something wrong.

**Full code that generated the error**

```python
In [1]: import gmt

In [2]: gmt.test()
```

**Full error message**

```

Loaded libgmt:
  binary dir: /home/user/anaconda3/envs/gy0/bin
  cores: 8
  grid layout: rows
  image layout: 
  library path: /home/user/anaconda3/envs/gy0/lib/libgmt.so
  padding: 2
  plugin dir: /home/user/anaconda3/envs/gy0/lib/gmt/plugins
  share dir: /home/user/anaconda3/envs/gy0/share/gmt
  version: 6.0.0
============================================================================ test session starts ============================================================================
platform linux -- Python 3.6.6, pytest-3.7.2, py-1.5.4, pluggy-0.7.1 -- /home/user/anaconda3/envs/gy0/bin/python
cachedir: .pytest_cache
Matplotlib: 2.2.3
Freetype: 2.9.1
rootdir: /home/user/prog, inifile:
plugins: mpl-0.9
collected 144 items / 1 errors                                                                                                                                              

================================================================================== ERRORS ===================================================================================
_________________________________________________________________ ERROR collecting gmt/sphinxext/gmtplot.py _________________________________________________________________
../anaconda3/envs/gy0/lib/python3.6/site-packages/gmt/sphinxext/gmtplot.py:39: in <module>
    from docutils import nodes
E   ModuleNotFoundError: No module named 'docutils'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 1 error in 1.31 seconds ==========================================================================
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-84e7c468e870> in <module>()
----> 1 gmt.test()

~/anaconda3/envs/gy0/lib/python3.6/site-packages/gmt/__init__.py in test(doctest, verbose, coverage, figures)
     92     args.append("gmt")
     93     status = pytest.main(args)
---> 94     assert status == 0, "Some tests have failed."

AssertionError: Some tests have failed.

```

**System information**

* Operating system:
* Python installation (Anaconda, system, ETS):
* Version of GMT:
* Version of Python:
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre></pre>
</details>

>  Name                    Version                   Build  Channel
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bokeh                     0.13.0                   py36_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.13            ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2018.8.13                py36_0    conda-forge
cftime                    1.0.1            py36h7eb728f_0    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
curl                      7.61.0               h93b3f91_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py36h470a237_0    conda-forge
dask                      0.18.2                     py_0    conda-forge
dask-core                 0.18.2                     py_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
dcw-gmt                   1.1.4                         0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.1                   py36_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
fontconfig                2.13.0               h65d0f4c_5    conda-forge
freetype                  2.9.1                h6debe1e_1    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
gdal                      2.2.4            py36hb00a9d7_1    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_2    conda-forge
gettext                   0.19.8.1                      0    conda-forge
ghostscript               9.22                 hfc679d8_1    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gmt                       6.0.0a17        blas_openblash0670df6_200  [blas_openblas]  conda-forge/label/dev
gmt-python                0+unknown                 <pip>
gshhg-gmt                 2.3.7                         0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
h5netcdf                  0.6.2                      py_0    conda-forge
h5py                      2.8.0            py36hb794570_1    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hc401514_1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.14.6                        0    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgdal                   2.2.4                h25f9fa3_7    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_2    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1                he6cff42_7    conda-forge
libpng                    1.6.35               ha92aebf_0    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a              hdfcc80b_21    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   2.32.1               h470a237_0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_3    conda-forge
locket                    0.2.0                      py_2    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.3            py36h8e2386c_0    conda-forge
more-itertools            4.3.0                    py36_0    conda-forge
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf4                   1.4.1            py36h62672b6_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
pcre                      8.41                 h470a237_2    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pixman                    0.34.0                        2    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
poppler                   0.61.1               h4d7e492_4    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.7                    py36_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.4                      py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_6    conda-forge
pytest                    3.7.2                    py36_0    conda-forge
pytest-mpl                0.9                        py_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
scipy                     1.1.0           py36_blas_openblash7943236_201  [blas_openblas]  conda-forge
setuptools                40.0.0                   py36_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sortedcontainers          2.0.4                      py_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.8                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.1              py36h470a237_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xarray                    0.10.8                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.2                h8c8a85c_6    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

**Comment by shaunwbell** [comment]
Your installation is missing docutils 

> `ModuleNotFoundError: No module named 'docutils'`

I had the same issue the other day - docutils, sphinx, and ghostscript for whatever reasons, weren't installed on my machine when I went through the instructions (maybe a missing entry in the requirements.txt file? - sphinx is there? I dunno, package management isn't my forte)

try installing these packages via `conda install docutils sphinx ghostscript` and see if your tests run

**Comment by leouieda** [comment]
Yeah, that was my fault. I included a sphinx extension in the package. I should have told pytest to ignore it. For now, if you install sphinx and docutils you should be fine.
