### ISSUE TITLE
Unable to import gmt

### ISSUE THREAD

**Issue by jbrussell** [GenericMappingTools/gmt-python#237]
**Description of the problem**
I followed installation instructions precisely but am unable to import gmt. I've also tried adding `export GMT_LIBRARY_PATH=$HOME/anaconda/envs/gmt6-python36/lib` to my `~/.bashrc`. 

To allow access to the environment kernel in jupyter, I've also run:
```
python -m ipykernel install --user --name gmt6-python36 --display-name "gmt6-python36"
conda install nb_conda_kernels
```
inside my gmt6-python36 environment

**Full code that generated the error**

```python
import gmt
```

**Full error message**

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/clib/loading.py in load_libgmt(env)
     41     try:
---> 42         libgmt = ctypes.CDLL(libpath)
     43         check_libgmt(libgmt)

~/anaconda/envs/gmt6-python36/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:

OSError: dlopen(/Users/russell/anaconda/envs/gmt6-python36/lib/libgmt.dylib, 6): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/russell/anaconda/envs/gmt6-python36/lib/libgdal.20.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

GMTCLibNotFoundError                      Traceback (most recent call last)
<ipython-input-1-550948f89e4b> in <module>
----> 1 import gmt
      2 # gmt.test()

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/__init__.py in <module>
     23 
     24 # Start our global modern mode session
---> 25 _begin()
     26 # Tell Python to run _end when shutting down
     27 _atexit.register(_end)

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/session_management.py in begin()
     15     """
     16     prefix = "gmt-python-session"
---> 17     with Session() as lib:
     18         lib.call_module("begin", prefix)
     19 

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/clib/session.py in __enter__(self)
    171 
    172         """
--> 173         self.create("gmt-python-session")
    174         # Need to store the version info because 'get_default' won't work after the
    175         # session is destroyed.

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/clib/session.py in create(self, name)
    319             "GMT_Create_Session",
    320             argtypes=[ctp.c_char_p, ctp.c_uint, ctp.c_uint, ctp.c_void_p],
--> 321             restype=ctp.c_void_p,
    322         )
    323 

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/clib/session.py in get_libgmt_func(self, name, argtypes, restype)
    269         """
    270         if not hasattr(self, "_libgmt"):
--> 271             self._libgmt = load_libgmt()
    272         function = getattr(self._libgmt, name)
    273         if argtypes is not None:

~/anaconda/envs/gmt6-python36/lib/python3.6/site-packages/gmt/clib/loading.py in load_libgmt(env)
     49             ]
     50         )
---> 51         raise GMTCLibNotFoundError(msg)
     52     return libgmt
     53 

GMTCLibNotFoundError: Error loading the GMT shared library '/Users/russell/anaconda/envs/gmt6-python36/lib/libgmt.dylib':
dlopen(/Users/russell/anaconda/envs/gmt6-python36/lib/libgmt.dylib, 6): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/russell/anaconda/envs/gmt6-python36/lib/libgdal.20.dylib
  Reason: image not found
```

**System information**

* Operating system: macOS Sierra 10.12.2
* Python installation (Anaconda, system, ETS): Anaconda
* Version of GMT: 6.0.0a17 
* Version of Python: 3.6.6
* Version of this package: Latest
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
# packages in environment at /Users/russell/anaconda/envs/gmt6-python36:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.0                 py36_1000    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.0.2                      py_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dcw-gmt                   1.1.4                         0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
fontconfig                2.13.1               hce039c3_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4            py36hb00a9d7_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
gettext                   0.19.8.1             h1f1d5ed_1    conda-forge
ghostscript               9.22                 hfc679d8_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmt                       6.0.0a17        blas_openblash0670df6_200  [blas_openblas]  conda-forge/label/dev
gmt-python                0+unknown                 <pip>
gshhg-gmt                 2.3.7                         0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.13.1               h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libdap4                   3.19.1               h18059cb_1    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgdal                   2.2.4                h7b1ea53_2  
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1              h34af652_200    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libpq                     10.5                 hf16a0db_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libspatialite             4.3.0a              ha12ebda_19  
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                2.2.3            py36h0e0179f_0    conda-forge
matplotlib-base           3.0.0            py36h45c993b_2    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
nb_conda_kernels          2.2.0                 py36_1000    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.0                 py36_1000    conda-forge
numpy                     1.15.2          py36_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h316dc23_3    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
poppler                   0.69.0               hfbecef8_0    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     5.0.1                         0    conda-forge
prometheus_client         0.4.2                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyrsistent                0.14.5           py36h470a237_1    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    3.10.0                py36_1000    conda-forge
pytest-mpl                0.10                       py_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.0                py36_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.5.0                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.1                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xarray                    0.11.0                py36_1000    conda-forge
xerces-c                  3.2.2                h5d6a6da_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
</pre>
</details>

**Comment by jbrussell** [comment]
I've also found that `gmt --version` yields the error
```
dyld: Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/russell/anaconda/envs/gmt6-python36/lib/libgdal.20.dylib
  Reason: image not found
Abort trap: 6
```

**Comment by jbrussell** [comment]
I've found the fix. The problem was that `gdal` was from conda-forge but `libgdal` was not. Simply running
`conda install -c conda-forge libgdal `
fixed the problem!

**Comment by leouieda** [comment]
@jbrussell thanks for posting and fixing the problem :) :tada: Best kind of bug report.

We've had a lot of trouble with mix ups between GMT and GDAL from conda. Still no good solution for solving this once and for all. But conda-forge seems to be working on making this better.
