### ISSUE TITLE
could not pass the python-test instalment

### ISSUE THREAD

**Issue by bridgeW** [GenericMappingTools/gmt-python#246]
**Description of the problem**
I followed the installing steps on https://www.gmtpython.xyz/latest/install.html, and all steps showed 
```shell   
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
All requested packages already installed.
````
But,
when I  running the following inside a Python interpreter:
     import gmt 
errors occured.

**Full code that generated the error**

```python
import gmt
```

**Full error message**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/__init__.py", line 25, in <module>
    _begin()
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/session_management.py", line 17, in begin
    with Session() as lib:
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/session.py", line 173, in __enter__
    self.create("gmt-python-session")
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/session.py", line 321, in create
    restype=ctp.c_void_p,
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/session.py", line 271, in get_libgmt_func
    self._libgmt = load_libgmt()
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/loading.py", line 43, in load_libgmt
    check_libgmt(libgmt)
  File "/home/joe/anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/loading.py", line 146, in check_libgmt
    raise GMTCLibError(msg)
gmt.exceptions.GMTCLibError: Error loading libgmt. Couldn't access function GMT_Get_Enum.

```

**System information**

* Operating system: Ubuntu 16.04 LTS ()
* Python installation (Anaconda, system, ETS): Anaconda
* Version of GMT: GMT-5.4.3
* Version of Python: Python 3.6.5
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.1.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cftime                    1.0.2.1                   <pip>
chardet                   3.0.4                 py36_1003    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.11.0                        0    conda-forge
dcw-gmt                   1.1.4                         0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
expat                     2.2.5                         0    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4            py36hb00a9d7_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
geotiff                   1.4.2                h700e5ad_5    conda-forge
gettext                   0.19.8.1                      0    conda-forge
ghostscript               9.22                 hfc679d8_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0                        0    conda-forge
gmt                       5.4.4           blas_openblash0670df6_201  [blas_openblas]  conda-forge
gmt-python                0+unknown                 <pip>
gshhg-gmt                 2.3.7                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.7                   py36_1002    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2018.0.0                      8  
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.16.1               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgdal                   2.2.4                ha6e4b24_6    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                          0    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1              h628ed10_200    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34                        0    conda-forge
libpq                     10.5                 he29860b_0    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mkl                       2018.0.2                      1  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.1.0                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
netCDF4                   1.4.2                     <pip>
nose                      1.3.7                    py36_2    conda-forge
numpy                     1.15.2          py36_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
numpy                     1.14.3                    <pip>
numpy-base                1.14.3           py36h0ea5e3f_1  
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
packaging                 18.0                       py_0    conda-forge
packaging                 17.1                      <pip>
pandas                    0.23.0                    <pip>
parso                     0.2.0                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pexpect                   4.5.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.1                      <pip>
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.5.3                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyparsing                 2.2.0                     <pip>
pyqt                      5.6.0                    py36_5    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    4.0.0                 py36_1000    conda-forge
pytest-mpl                0.10                       py_0    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                     <pip>
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.20.1                py36_1000    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.2                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xarray                    0.10.4                    <pip>
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

</pre>
</details>

**Comment by seisman** [comment]
From the output of `conda list`, I can see that your conda installs GMT 5.4.4, rather than 6.0.0. Maybe you forgot to add conda-forge's dev channel.
