### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/gmt-python#263]
Right now, this project is called "GMT/Python". But that's not a valid package name so we `import gmt`. But we can't call our repository, PyPI and conda packages `gmt` so they'll have to be `gmt-python`. This is kind of crazy. Plus, `import gmt` confuses a lot of beginners.

Clearly we need a new name.

Both `pygmt` and `gmtpy` have been used before but they were never registered on PyPI so we can still use those names. I don't really like those two options much but they are certainly better than what we have right now.

**Are there any other suggestions?**

**Comment by leouieda** [comment]
Pinging @GenericMappingTools/gmt-python @liamtoney @weiji14 @akshmakov @mjziebarth

**Comment by weiji14** [comment]
Why not just go with GMT-Python? Use `gmt-python` as the PyPI package name just to be consistent with conda, and `import gmtpython` to import the package (no hyphen). This is about the same as [scikit-image](https://scikit-image.org/) and [scikit-learn](https://scikit-learn.org) which uses `import skimage` and `import sklearn` respectively (note no hyphen also).

Oh, and for reference on package naming, there's [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by leouieda** [comment]
That's a fair point but then we're not any better off. It's still confusing that you install one thing and import another. That's something I really dislike about scikit-learn and scikit-image. I'm sure they'd rename if they could but they've already been around for too long. We don't have an official release yet so it's the perfect time to do this right. I would prefer to have the repository, import, and PyPI package names be the same.  

If we go with `gmtpython` then I'd prefer to never have the hyphen in there. We can always `import gmtpython as gp` or `import gmtpython as gmt` to keep things short. This isn't a bad idea actually and would be minimally disruptive.

**Comment by liamtoney** [comment]
This option would be shorter, and could allow for a repo name that is also consistent:
```
conda install pygmt
```
```python
import pygmt
```

[GenericMappingTools/PyGMT](https://github.com/GenericMappingTools/gmt-python)

# PyGMT
**A Python interface to the Generic Mapping Tools (GMT)**

**Comment by liamtoney** [comment]
Or, taking @weiji14's idea above and making it entirely consistent, even with case. The title is less stylish, but then things are truly unambiguous, which is valuable in my opinion...
```
conda install gmtpython
```
```python
import gmtpython as gmt
```

[GenericMappingTools/gmtpython](https://github.com/GenericMappingTools/gmt-python)

# gmtpython
**A Python interface to the Generic Mapping Tools (GMT)**

**Comment by leouieda** [comment]
@liamtoney that's my favorite between `pygmt` and `gmtpy`. I'm still hoping for some clever/funny name to come along, though :wink: 

I know @PaulWessel is a Monty Python fan so something related to that might be interesting. Are there any Monty Python jokes related to mapping?

**Comment by leouieda** [comment]
@liamtoney actually, there is already an "airspeed velocity" Python package (https://github.com/airspeed-velocity/asv) :(

**Comment by liamtoney** [comment]
And that above comment was in jest, anyhow. :)

On a more serious note, while I like the idea of a "punny" name, isn't it important to have a short package name that gives some indication of the package topic?

**Comment by leouieda** [comment]
Yeah, having a clear and concise name would be optimal. Just putting it out there in case anyone has a good idea :)

**Comment by leouieda** [comment]
I'm leaning towards `pygmt`. Can I get a :+1: or :-1: on that?

**Comment by weiji14** [comment]
> @liamtoney that's my favorite between `pygmt` and `gmtpy`. I'm still hoping for some clever/funny name to come along, though :wink:

No idea why, but I had this dream this morning and woke up with this name "**GM**igh**T**y". Since GMT is a powerful and awesome library, [*mighty*](https://www.wordnik.com/words/mighty) seems like a good word for it :smile: And as you've all mentioned, we could do something like:

    import gmighty as gmt

I did consider something like gmightpy or gmighpy, just to have the *Py* of Python in it, but they're hard to pronounce and *Ty* sounds enough like *Py* :man_shrugging:.

**Comment by leouieda** [comment]
@weiji14 thanks for setting that up! These Github apps are really helpful. 

OK, so can we get a vote on these names:

/polls pygmt gmtpy gmtpython

(sorry @weiji14, I have a really hard time reading gmighty and pronouncing it in my head :)

**Comment by leouieda** [comment]
The bot is not working for some reason. So let's not go with a full democracy. Instead, I propose using `pygmt`. Please add a reaction to this comment with either :+1: or :-1:  (click on the + :smiley: button).

**Comment by leouieda** [comment]
Well that sucks, someone took pygmt.org since yesterday.

**Comment by seisman** [comment]
@leouieda How do you know that pygmt.org was taken?

Godaddy shows it's still available. See https://www.godaddy.com/domainsearch/find?isc=cjcbh99&checkAvail=1&tmskey=&domainToCheck=pygmt.org

**Comment by leouieda** [comment]
Yeah, it was my mistake. I had it on my cart and it showed up as unavailable.

**Comment by leouieda** [comment]
The rename was successful! Please update your github links. The docs are now hosted on http://www.pygmt.org/ and the name is register on PyPI. Still waiting for SSL certificates to enable https and the gitter room to rename fully. I'm setting up forwarding from the old gmtpython.xyz.
