### ISSUE TITLE
gmtpy

### ISSUE THREAD

**Issue by hvasbath** [GenericMappingTools/gmt-python#27]
Just to mention that this library here exists since around 7years by @emolch
https://github.com/emolch/gmtpy

Examples and usage here:
http://emolch.github.io/gmtpy/

Before you restart doing something that has been done already?
Maybe this can be brought together?

**Comment by leouieda** [comment]
@hvasbath I'm well aware of the other GMT python attempts: https://genericmappingtools.github.io/gmt-python/design.html#previous-work 

I'm taking a very different approach to the wrapper and would probably have to rewrite most of any of those libraries. Plus, they are made for GMT5. I'm working with Paul Wessel to make GMT6 and this library is a being developed side-by-side with it.
