### ISSUE TITLE
gmt.show() not working in ipython console

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt-python#28]
`gmt.show()` can display figure in **ipython notebook** but not in **ipython console**.
```
$ ipython
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import gmt

In [2]: gmt.figure()

In [3]: gmt.pscoast(R='-90/-70/0/20', J='M6i', G='chocolate',
   ...:             S='skyblue', P=True, B='afg')
   ...:             

In [4]: gmt.show()
<IPython.core.display.Image object>

In [5]: 
```
It will be better if `gmt.show()` can open a new figure window just like what `matplotlib.pyplot.show` does.

**Comment by leouieda** [comment]
@seisman currently the `show` function only generates the image for the notebook. I'll look into making it pop up using matplotlib and `imshow`. This might help us to get `sphinx-gallery` working as well. Thanks for the suggestion!

**Comment by leouieda** [comment]
@seisman I tried implementing this using matplotlib `imshow` but it just looks really bad. It's not a viable solutions.

But since GMT generates PDF output, I'll try to make it open an external application with the PDF preview (possibly the browser).

**Comment by shicks-seismo** [comment]
@leouieda, not sure if this is possible, but for quick previewing, is there any way to rasterize the drawing first and then use `show`?

**Comment by leouieda** [comment]
@shicks-seismo that's pretty much what `show` does right now: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/figure.py#L219

But it only works for the notebook. Opening the external window would be an added option (`external=True`) that would open up the preview. It could be a raster but if we're opening a program window anyway we might as well make it PDF.

**Comment by leouieda** [comment]
I implemented this by introducing a new keyword argument:

    fig.show(external=True)

Will open a PDF preview of the figure in the default PDF viewer. It still won't work for scripts because the command is non-blocking and so the script continues to run and eventually deletes the preview. I might add an argument to `savefig` to make it pop up the saved figure (also non-blocking) so that it can be used in scripts.
