### ISSUE TITLE
@rpath/libicui18n.58.dylib Reason: image not found

### ISSUE THREAD

**Issue by echavess** [GenericMappingTools/gmt-python#32]
Hi all, 
I have installed the code through anaconda (python 3.5) and I am getting the next error:

`>> import gmt `

```
OSError: dlopen(libgmt.dylib, 6): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /opt/anaconda/lib/libgdal.20.dylib
  Reason: image not found
```

Any ideas how can I fix this issue? I am working on Mac OS X. 

Thanks in advance, 
Esteban

**Comment by shicks-seismo** [comment]
Hi Esteban

See if either of the following closed issues help - looks like you may change the way you have done the  installation:
[https://github.com/GenericMappingTools/gmt-python/issues/29](https://github.com/GenericMappingTools/gmt-python/issues/29)
[https://github.com/GenericMappingTools/gmt-python/issues/30](https://github.com/GenericMappingTools/gmt-python/issues/30)

**Comment by leouieda** [comment]
@shicks-seismo beat me to the answer 😄 

Please follow the instruction for creating a conda environment in #30. This happens when you mix binaries from the default anaconda channel and conda-forge. 

I'll add these instructions to the docs (#33). Other people are bound to run into the same problem.

**Comment by echavess** [comment]
Thanks @shicks-seismo and @leouieda, will try that. 

Cheers,

**Comment by leouieda** [comment]
Hi @echavess please let us know if the instructions worked for you.

**Comment by echavess** [comment]
@leouieda I was reading the discussion in #30 but I don't use Jupyter notebooks, so I am not sure if installing a separate environment works for me. My intention was to implement some mapping within a code I am wrote for earthquake source parameters and it does depend on some other libraries/dependencies. 

I guess I will wait until I can do conda install gmt-python

Thanks, 
Esteban

**Comment by leouieda** [comment]
@echavess you don't need to use the notebook to use conda envs. You can run any command inside an environment (even `python my_script.py`) and it should work.

**Comment by leouieda** [comment]
There isn't much you can do with the library yet because I'm still working out the basis needed for some features. Once that is done, it would be relatively easy to start wrapping more and more GMT commands.

**Comment by utpalkumariesas** [comment]
I can easily install and use GMT/Python in a new installation of Anaconda and even in the new environment. I think it is an awesome project. But the problem is its conflict with other packages.  I did a fresh installation of anaconda to install this and it got installed smoothly. But then I have issues with the basemap. I cannot use basemap properly as before.
`ModuleNotFoundError: No module named 'mpl_toolkits.basemap'`
I cannot even update basemap. I get the following error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - basemap
  - gdal
  - python 3.6*

**Comment by leouieda** [comment]
@utpalkumariesas if you created a new empty environment, then it wouldn't have basemap installed in it by default. The purpose of the environments is to have separate installations as a way to avoid these dependency clashes. 

When you try to install basemap in your empty environment, are you running `conda install basemap` or `conda install basemap -c conda-forge`? Mixing packages from the default Anaconda and conda-forge can cause dependency problems, particularly for binary packages like gdal.

**Comment by utpalkumariesas** [comment]
Yes, exactly! I face dependency issues when I use Anaconda default basemap/matplotlib with the GMT-Python installation or the other way round. But GMT-Python installation in the new environment is flawless. I wish to use matplotlib scripts along with GMT-Python which seems to be incompatible. If this problem can be addressed then I believe it would become perfect tool required for mapping in python.

**Comment by leouieda** [comment]
@utpalkumariesas could you try creating an empty environment and running:

    conda install -c conda-forge/label/dev -c conda-forge gmt numpy matplotlib basemap

This ensures that you get all your packages form conda-forge and avoids the conflicts.
