### ISSUE TITLE
PackageNotFoundError 

### ISSUE THREAD

**Issue by egayer** [GenericMappingTools/gmt-python#84]
Hi guys, 
Just wanted to install gmt following the install recipe but

> conda install gmt -c conda-forge/label/dev

returns

> PackageNotFoundError: Packages missing in current channels:
> 
>   - gmt -> blas 1.1 openblas
>   - gmt -> dcw-gmt
>   - gmt -> fftw
>   - gmt -> ghostscript
>   - gmt -> gshhg-gmt
>   - gmt -> @blas_openblas
> 
> We have searched for the packages in the following channels:
> 
>   - https://conda.anaconda.org/conda-forge/label/dev/osx-64
>   - https://conda.anaconda.org/conda-forge/label/dev/noarch
>   - https://repo.continuum.io/pkgs/main/osx-64
>   - https://repo.continuum.io/pkgs/main/noarch
>   - https://repo.continuum.io/pkgs/free/osx-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/osx-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/osx-64
>   - https://repo.continuum.io/pkgs/pro/noarch

what should I do ?
thanks

**Comment by leouieda** [comment]
Hi @egayer are you on Windows?

**Comment by egayer** [comment]
nope on osX
Python 3.6.3 |Anaconda, Inc.| and conda version : 4.3.30

**Comment by leouieda** [comment]
Could you try running this instead?

```
conda install gmt -c conda-forge/label/dev -c conda-forge
```

**Comment by leouieda** [comment]
It seems that conda is looking for all GMT dependencies on the development channel, which it shouldn't do. This might have gone unnoticed because of my particular configuration.

**Comment by egayer** [comment]
it worked !
however

`import gmt` works
but then `gmt.test()` returns 

> ModuleNotFoundError:

 No module named 'pytest'

**Comment by leouieda** [comment]
@egayer thanks for the feedback! I forgot to mention that you need to install `pytest` and `pytest-mpl` in order to run the tests. Fixing this in #87.

You need to install them running:

```
conda install pytest pytest-mpl -c conda-forge
```

Then the tests should work.

I had no idea that things were crashing in spyder. Would you mind opening a separate issue for this? It shouldn't crash the program or give such weird errors.
